export interface PersonelAtamaModel {
  id: string;
  fullName: string;
  sirketAd: string;
  sirketId: string;
  subeAd?: string;
  subeId?: string;
  departmanAd?: string;
  departmanId?: string;
  pozisyonAd?: string;
  pozisyonId?: string;
  rolAd: string;
  yoneticiId?: string;
  yoneticiAd?: string;
  sozlesmeTuruValue: number;
  pozisyonBaslangicTarih: Date;
  pozisyonBitisTarih?: Date;
  calismaTakvimAd: string;
  izinKuralAd: string;
  isActive: boolean;
  createdAt: Date;
  createUserId?: string;
  createUserName?: string;
  updateAt?: Date;
  updateUserId?: string;
  updateUserName?: string;
  isDeleted: boolean;
  deleteAt?: Date;
}
