// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelYonetim.Server.Infrastructure.Context;

#nullable disable

namespace PersonelYonetim.Server.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322191636_yoneticiTipi_RolTipi")]
    partial class yoneticiTipi_RolTipi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Departmanlar.Departman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SirketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.HasIndex("SubeId");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.IzinTalepler.IzinTalep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("BaslangicTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("BitisTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DegerlendirenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DegerlendirilmeTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DegerlendirmeDurumu")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IzinTipi")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DegerlendirenId");

                    b.HasIndex("PersonelId");

                    b.ToTable("IzinTalepleri");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.PersonelAtamalar.PersonelAtama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CalismaSekli")
                        .HasColumnType("int");

                    b.Property<Guid?>("DepartmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PozisyonBaslamaTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PozisyonBitisTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PozisyonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolTipi")
                        .HasColumnType("int");

                    b.Property<Guid>("SirketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SozlesmeBitisTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SozlesmeTuru")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("SirketId");

                    b.HasIndex("SubeId");

                    b.ToTable("PersonelAtama");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Personeller.Personel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DogumTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("IseGirisTarihi")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProfilResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YoneticiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("YoneticiId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Pozisyonlar.Pozisyon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SirketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("SirketId");

                    b.ToTable("Pozisyonlar");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Roller.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SirketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId", "SirketId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Rols.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Sirketler.Sirket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sirketler");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Subeler.Sube", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SirketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Tokenler.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tokenler");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(MAX)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Departmanlar.Departman", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Sirketler.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PersonelYonetim.Server.Domain.Subeler.Sube", "Sube")
                        .WithMany("Departmanlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sirket");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.IzinTalepler.IzinTalep", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Personeller.Personel", "Degerlendiren")
                        .WithMany()
                        .HasForeignKey("DegerlendirenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PersonelYonetim.Server.Domain.Personeller.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Degerlendiren");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.PersonelAtamalar.PersonelAtama", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Departmanlar.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PersonelYonetim.Server.Domain.Personeller.Personel", "Personel")
                        .WithMany("PersonelAtamalar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelYonetim.Server.Domain.Pozisyonlar.Pozisyon", "Pozisyon")
                        .WithMany()
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PersonelYonetim.Server.Domain.Sirketler.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PersonelYonetim.Server.Domain.Subeler.Sube", "Sube")
                        .WithMany()
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Departman");

                    b.Navigation("Personel");

                    b.Navigation("Pozisyon");

                    b.Navigation("Sirket");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Personeller.Personel", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Users.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("PersonelYonetim.Server.Domain.Personeller.Personel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelYonetim.Server.Domain.Personeller.Personel", "Yonetici")
                        .WithMany()
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Adres", "Adres", b1 =>
                        {
                            b1.Property<Guid>("PersonelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ilce")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("İlçe");

                            b1.Property<string>("Sehir")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Şehir");

                            b1.Property<string>("TamAdres")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TamAdres");

                            b1.Property<string>("Ulke")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Ülke");

                            b1.HasKey("PersonelId");

                            b1.ToTable("Personeller");

                            b1.WithOwner()
                                .HasForeignKey("PersonelId");
                        });

                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Iletisim", "Iletisim", b1 =>
                        {
                            b1.Property<Guid>("PersonelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Eposta")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Eposta");

                            b1.Property<string>("Telefon")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Telefon");

                            b1.HasKey("PersonelId");

                            b1.HasIndex("Eposta")
                                .IsUnique();

                            b1.ToTable("Personeller");

                            b1.WithOwner()
                                .HasForeignKey("PersonelId");
                        });

                    b.Navigation("Adres")
                        .IsRequired();

                    b.Navigation("Iletisim")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Pozisyonlar.Pozisyon", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Departmanlar.Departman", null)
                        .WithMany("Pozisyonlar")
                        .HasForeignKey("DepartmanId");

                    b.HasOne("PersonelYonetim.Server.Domain.Sirketler.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Sirketler.Sirket", b =>
                {
                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Adres", "Adres", b1 =>
                        {
                            b1.Property<Guid>("SirketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ilce")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("İlçe");

                            b1.Property<string>("Sehir")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Şehir");

                            b1.Property<string>("TamAdres")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TamAdres");

                            b1.Property<string>("Ulke")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Ülke");

                            b1.HasKey("SirketId");

                            b1.ToTable("Sirketler");

                            b1.WithOwner()
                                .HasForeignKey("SirketId");
                        });

                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Iletisim", "Iletisim", b1 =>
                        {
                            b1.Property<Guid>("SirketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Eposta")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Eposta");

                            b1.Property<string>("Telefon")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Telefon");

                            b1.HasKey("SirketId");

                            b1.HasIndex("Eposta")
                                .IsUnique();

                            b1.ToTable("Sirketler");

                            b1.WithOwner()
                                .HasForeignKey("SirketId");
                        });

                    b.Navigation("Adres")
                        .IsRequired();

                    b.Navigation("Iletisim")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Subeler.Sube", b =>
                {
                    b.HasOne("PersonelYonetim.Server.Domain.Sirketler.Sirket", "Sirket")
                        .WithMany("Subeler")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Adres", "Adres", b1 =>
                        {
                            b1.Property<Guid>("SubeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ilce")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("İlçe");

                            b1.Property<string>("Sehir")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Şehir");

                            b1.Property<string>("TamAdres")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TamAdres");

                            b1.Property<string>("Ulke")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Ülke");

                            b1.HasKey("SubeId");

                            b1.ToTable("Subeler");

                            b1.WithOwner()
                                .HasForeignKey("SubeId");
                        });

                    b.OwnsOne("PersonelYonetim.Server.Domain.Personeller.Iletisim", "Iletisim", b1 =>
                        {
                            b1.Property<Guid>("SubeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Eposta")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Eposta");

                            b1.Property<string>("Telefon")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Telefon");

                            b1.HasKey("SubeId");

                            b1.HasIndex("Eposta")
                                .IsUnique();

                            b1.ToTable("Subeler");

                            b1.WithOwner()
                                .HasForeignKey("SubeId");
                        });

                    b.Navigation("Adres")
                        .IsRequired();

                    b.Navigation("Iletisim")
                        .IsRequired();

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Departmanlar.Departman", b =>
                {
                    b.Navigation("Pozisyonlar");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Personeller.Personel", b =>
                {
                    b.Navigation("PersonelAtamalar");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Sirketler.Sirket", b =>
                {
                    b.Navigation("Subeler");
                });

            modelBuilder.Entity("PersonelYonetim.Server.Domain.Subeler.Sube", b =>
                {
                    b.Navigation("Departmanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
